volumes:
  postgres_data: {}
  prom_data: {}
  redis_data: {}

services:
  #  harp:
  #    image: makersquad/harp-proxy:0.5.0rc2
  #    volumes:
  #      - ./harp.yaml:/etc/harp.yaml
  #    ports:
  #      - 7080:7080
  #      - 7090:7090

  api1:
    image: mccutchen/go-httpbin
    ports:
      - 7091:8080

  api2:
    image: mccutchen/go-httpbin
    ports:
      - 7093:8080

  postgres:
    image: postgres:16
    ports:
      - 7432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # https://github.com/locustio/locust/issues/150 (multiple hosts)
  locust:
    image: locustio/locust
    ports:
      - 7099:8089
    volumes:
      - ./locust/config:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:7090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust-worker:
    image: locustio/locust
    volumes:
      - ./locust/config:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust
    deploy:
      mode: replicated
      replicas: 5
      endpoint_mode: vip
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust-exporter:
    image: containersol/locust_exporter
    command: --locust.uri=http://locust:8089
    ports:
      - 7098:9646

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 7070:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=demo
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
