fullnameOverride: harp

harp:
  container:
    arguments: [ --enable, rules ]
    env:
      LOGGING_SQL: info

postgresql:
  auth:
    database: harp
    password: password
    username: harp
  enabled: true
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 30001

endpoints:
  - name: api1
    port: 8080
    serviceName: api1-proxy
    remote:
      min_pool_size: 2
      endpoints:
        - { url: "http://api1-internal/" }
        - { url: "http://api2-internal/" }
        - { url: "http://api3-internal/", pools: [fallback] }
        - { url: "http://api4-internal/", pools: [fallback] }
      probe:
        method: GET
        path: "/get"
        interval: 5
        #verify: False
      break_on: [network_error]

  - name: api2
    port: 8081
    serviceName: api2-proxy
    remote:
      min_pool_size: 2
      endpoints:
        - { url: "http://api3-internal/" }
        - { url: "http://api4-internal/" }
        - { url: "http://api1-internal/", pools: [fallback] }
        - { url: "http://api2-internal/", pools: [fallback] }
      probe:
        method: GET
        path: "/get"
        interval: 5
        #verify: False
      break_on: [network_error]


settings:
  storage:
    url: postgresql+asyncpg://harp:password@harp-postgresql/harp

  rules:
    'api1':
      'GET /get':
        '':
          pass

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dashboard.harp.demo
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - dashboard.harp.demo
      secretName: demo-tls
