{
 "title": "Harp Metro",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transaction Rate and Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(requests_time_count{path=\"\"}[$__rate_interval])",
     "legendFormat": "Count ({{method}})"
    },
    {
     "expr": "rate(requests_time_sum{path=\"\"}[$__rate_interval]) / rate(requests_time_count{path=\"\"}[$__rate_interval])",
     "legendFormat": "Time ({{method}})"
    }
   ]
  },
  {
   "title": "Responses Count by Status (200, ...)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status)(rate(responses_count_total[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "storage_transactions\n", "legendFormat": "{{__name__}}" },
    { "expr": "storage_messages\n", "legendFormat": "{{__name__}}" },
    { "expr": "storage_blobs\n", "legendFormat": "{{__name__}}" },
    { "expr": "storage_blobs_orphans\n", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Objects Created (DB Storage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(started_at, $__interval),\n  count(id) AS \"transactions created\"\nFROM\n  transactions\nWHERE\n  $__timeFilter(started_at)\nGROUP BY\n  1\nORDER BY\n  $__timeGroup(started_at, $__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at, $__interval),\n  count(id) AS \"blobs created\"\nFROM\n  blobs\nWHERE\n  $__timeFilter(created_at)\nGROUP BY\n  1\nORDER BY\n  $__timeGroup(created_at, $__interval)"
    }
   ]
  },
  {
   "title": "Proxy total time vs Forward time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(proxy_time_full_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_full_count{}[$__rate_interval])) without (method,name)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (rate(proxy_time_forward_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_forward_count{}[$__rate_interval])) without (method,name)\n\n",
     "legendFormat": "Forward"
    }
   ]
  },
  {
   "title": "Proxy overhead",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((sum (rate(proxy_time_full_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_full_count{}[$__rate_interval])) without (method,name))\n-\n(sum (rate(proxy_time_forward_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_forward_count{}[$__rate_interval])) without (method,name)))",
     "legendFormat": "Overhead"
    },
    {
     "expr": "\n((sum (rate(proxy_time_full_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_full_count{}[$__rate_interval])) without (method,name))\n-\n(sum (rate(proxy_time_forward_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_forward_count{}[$__rate_interval])) without (method,name)))\n\n/\n\n(sum (rate(proxy_time_full_sum{}[$__rate_interval])) without (method,name)\n/\nsum (rate(proxy_time_full_count{}[$__rate_interval])) without (method,name))\n",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}